"""add_soft_delete_to_todos

Revision ID: 10efc36e39e2
Revises: f37b5e709d11
Create Date: 2026-03-15 12:54:46.764986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10efc36e39e2'
down_revision: Union[str, Sequence[str], None] = 'f37b5e709d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
