"""add_soft_delete_to_todos

Revision ID: f37b5e709d11
Revises: 20a3f9d2c9c1
Create Date: 2026-03-15 12:54:20.981848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37b5e709d11'
down_revision: Union[str, Sequence[str], None] = '20a3f9d2c9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
